spring:
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/moim
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'